apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.AppNamespace}}
  name: db
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
