apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.AppNamespace}}
  name: result-service
spec:
  selector:
    app: result
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003