apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.AppNamespace}}
  name: result
  labels: 
    app: result-deployment
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      namespace: {{ .Values.AppNamespace}}
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result
          resources:
            limits:
              cpu: "200m"
              memory: "500Mi"
          ports:
            - containerPort: 80