apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.AppNamespace}}
  name: voting-app-service
  labels:
    app: {{ .Values.VotingAppName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.VotingAppName }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      
